# Usa la imagen base oficial de MySQL
FROM mysql:latest

# Establece la contraseña de root para MySQL
ENV MYSQL_ROOT_PASSWORD=password

# Opcional: crea una base de datos al iniciar el contenedor
ENV MYSQL_DATABASE=my_database

# Opcional: define el conjunto de caracteres y la collation por defecto
ENV MYSQL_CHARSET=utf8mb4
ENV MYSQL_COLLATION=utf8mb4_unicode_ci

