services:
  nodejs-backend:
    build: ./nodejs-backend
    ports:
      - "3000:3000"
    depends_on:
      - mysql-db
      - redis

  mysql-db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Bios123
      MYSQL_DATABASE: bios_db
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mysql-data:
